# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Craftsman
email: david.sosa.valdes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Advanced CLI for Codeigniter 3.0
baseurl: "/Craftsman" # the subpath of your site, e.g. /blog
url: "https://github.com/davidsosavaldes" # the base hostname & protocol for your site
github_username: davidsosavaldes

# Theme settings
issues: "/issues"
releases: "/wiki/Release-Notes"
motto: "Provides a number of helpful commands for your use while developing your application."
version: 3.3.0
demo: "https://www.youtube-nocookie.com/embed/JA51oVUoWRc?rel=0&amp;showinfo=0&amp;hd=1"
license: 'MIT'

# Build settings
markdown: kramdown

sass:
    style: :compressed

include: ['_pages']