# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Craftsman
description: 'Advanced CLI for Codeigniter 3.0'
baseurl: '/Craftsman'
repository: davidsosavaldes/Craftsman # <username>/<repository>

# User settings
github:
  user_fullname: 'David Sosa Valdes'
  licence: MIT # repository licence name
twitter:
  username: itsdsv
  hashtags: 'CLI, Codeigniter, Symfony Console Component' # without symbols

# Build settings
markdown: kramdown
include: ['_pages']
gems: 
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist