#!/usr/bin/env php
<?php

/**
 * CLI Codeigniter Crafstman
 *
 * @author     David Sosa Valdes <https://github.com/davidsosavaldes>
 * @license    MIT License
 * @link       https://github.com/davidsosavaldes/Craftsman
 * @copyright  Copyright (c) 2015, David Sosa Valdes.
 */

define('ROOTPATH', __DIR__.DIRECTORY_SEPARATOR);

use Codeigniter\Migrations\Run;
use Codeigniter\Migrations\Rollback;
use Codeigniter\Migrations\Refresh;
use Codeigniter\Migrations\Reset;
use Codeigniter\Migrations\Info;
use Codeigniter\Migrations\Version;
use Codeigniter\Migrations\Latest;
use Codeigniter\Migrations\Generate;

use Symfony\Component\Console\Application;

// Create CodeIgniter instance and add the extended packages.
$CI = require ROOTPATH.'src/ci_instance.php';
$CI->load->add_package_path(ROOTPATH.'src/Extend');

/**
 * We need to load the special migration settings.
 * 
 * Config file path:
 * 		src/Extend/config/migration.php
 * 		
 * @var array
 */
$CI->config->load('migration', TRUE, TRUE);
if ($params = $CI->config->item('migration')) 
{
	$CI->load->library('migration', $params);

	$commands = array(
		new Codeigniter\Migrations\Run($CI->migration),
		new Codeigniter\Migrations\Rollback(),
		new Codeigniter\Migrations\Refresh(),
		new Codeigniter\Migrations\Reset(),
		new Codeigniter\Migrations\Info(),
		new Codeigniter\Migrations\Version(),
		new Codeigniter\Migrations\Latest(),
		new Codeigniter\Migrations\Generate()
	);
	
	$application = new Application('Craftsman', '3.1.0');
	foreach ($commands as $key => $command) {
		$application->add($command);
	}
	$application->run();
}
else
{
	throw new \RuntimeException("Craftsman migration settings does not appear to set correctly.");
}
