#!/usr/bin/env php
<?php
require __DIR__.'/../../autoload.php';

define('TEMPLATEPATH', __DIR__.'/templates/Codeigniter'.DIRECTORY_SEPARATOR);

use Symfony\Component\Console\Application;
use Codeigniter\Migrations\Create as MigrationsCreateCommand;

$migration = new MigrationsCreateCommand(); 

$application = new Application('Craftsman','1.0.0');
$application->add($migration);
$application->run();