#!/usr/bin/env php
<?php
# PRODUCTION
require __DIR__.'/../../autoload.php';

# DEVELOPMENT
#require __DIR__.'/vendor/autoload.php';

define('TEMPLATEPATH', __DIR__.'/templates/Codeigniter'.DIRECTORY_SEPARATOR);

use Symfony\Component\Console\Application;

use Codeigniter\Migrations\Generate as MigrationsGenerateCommand;
use Codeigniter\Migrations\Run as MigrationsRunCommand;
use Codeigniter\Migrations\Rollback as MigrationsRollbackCommand;
use Codeigniter\Migrations\Refresh as MigrationsRefreshCommand;
use Codeigniter\Migrations\Reset as MigrationsResetCommand;

$commands = array(
	new MigrationsGenerateCommand(),
	new MigrationsRunCommand(),
	new MigrationsRollbackCommand(),
	new MigrationsResetCommand(),
	new MigrationsRefreshCommand(),
);

$application = new Application('Craftsman','1.0.0');

foreach ($commands as $key => $command) {
	$application->add($command);
}
$application->run();